spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pjt3?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Abcd123!

  mail:
    host: smtp.gmail.com
    port: 587
    username: # fill out
    password: # fill out
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: create

elasticsearch:
  host: 34.47.118.187:9200
  username: elastic
  password: Abcd123!

cloud:
  aws:
    cloudfront:
      domain: https://dy5ta30ib886x.cloudfront.net
    s3:
      bucket: pjt3
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: # fill out
      secretKey: # fill out

jwt:
  secret: mecha_kawa_shiochan_

coolsms:
  apiKey: # fill out
  secret: # fill out
  sender: # fill out # 발신 번호
  enable: false # false로 설정 시 문자 전송 로직을 스킵함