server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: reserve-service
          uri: http://localhost:9001
          predicates:
            - Path=v1/reserve/**
        - id: common-service
          uri: http://localhost:9002
          predicates:
            - Path=v1/common/**

      filter:
        rewrite-path:
          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka