server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins:
            - '*' # 허용하려는 도메인
          allow-credentials: true # 요청 시 인증 정보를 전송하도록 허가
          allowedHeaders: '*' # 허용하려는 헤더
          allowedMethods: # 허용하려는 HTTP 메서드
            - PUT
            - GET
            - POST
            - DELETE
            - OPTIONS
    gateway:
      routes:
        ########### RESERVE-SERVICE ###########
        ##### [reserve-service] REST APIs #####
        - id: reserve-service
          uri: http://localhost:9091 #2) localhost:9000 말고 여기로 보내줌
          predicates: # 1) 여기로 접속 시도하면
            - Path=/v1/reserve/**, /v2/reserve/**

        ########### COMMON-SERVICE ############
        ### [common-service] View Endpoints ###
        - id: common-service
          uri: http://localhost:9093
          predicates:
            - Path=/, /auth/**, /member/**, /store/**, /reserve/**, /noti/**
        ###### [common-service] REST APIs #####
        - id: common-service
          uri: http://localhost:9093
          predicates:
            - Path=/v1/auth/**, /v2/auth/**, /v1/member/**, /v1/store/**
        ########### static files ##############
        - id: common-service
          uri: http://localhost:9093
          predicates:
            - Path=/css/**, /js/**, /icon/**, /img/**

      filter:
        rewrite-path:
          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://43.203.83.252:8761/eureka